import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  public data = [
    {
      id: 1,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Apr 03 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      postem: "Chef de Services Production et Maintenance Applicatif",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      file: "3.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/3.pdf",
      nomInt: "4"
    },
    {
      id: 2,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2019 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Feb 22 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      postem: "Chef de Services Production et Maintenance Applicatif",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      file: "1.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
      nomInt: "4"
    },
    {
      id: 3,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      postem: "Chef de Services Production et Maintenance Applicatif",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      file: "4.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/4.pdf",
      nomInt: "5"
    },
    {
      id: 4,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      file: "5.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/5.pdf",
      postem: "Chef de Services Production et Maintenance Applicatif",
      nomInt: "4"
    },
    {
      id: 5,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Feb 31 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      postem: "Chef de Services Production et Maintenance Applicatif",
      matricule: "060210",
      statut: false,
      file: "2.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/2.pdf",
      nomInt: "5"
    },
    {
      id: 6,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Mar 31 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      postem: "Chef de Services Production et Maintenance Applicatif",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      file: "1.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
      nomInt: "4"
    },
    {
      id: 7,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      postem: "Chef de Services Production et Maintenance Applicatif",
      matricule: "060210",
      statut: false,
      file: "3.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/3.pdf",
      nomInt: "5"
    },
    {
      id: 8,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      nomInt: "4",
      file: "1.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
      postem: "Chef de Services Production et Maintenance Applicatif",
    },
    {
      id: 9,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      postem: "Chef de Services Production et Maintenance Applicatif",
      matricule: "060210",
      statut: false,
      file: "4.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/4.pdf",
      nomInt: "4"
    },
    {
      id: 10,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      postem: "Chef de Services Production et Maintenance Applicatif",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      statut: false,
      file: "5.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/5.pdf",
      nomInt: "4"
    },
    {
      id: 11,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      nomInt: "4",
      file: "2.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/2.pdf",
      postem: "Chef de Services Production et Maintenance Applicatif",
    },
    {
      id: 12,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      postem: "Chef de Services Production et Maintenance Applicatif",
      matricule: "060210",
      statut: false,
      file: "5.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/5.pdf",
      nomInt: "4"
    },
    {
      id: 13,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      nomInt: "4",
      file: "3.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/3.pdf",
      postem: "Chef de Services Production et Maintenance Applicatif",
    },
    {
      id: 14,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      postem: "Chef de Services Production et Maintenance Applicatif",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      file: "2.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
      nomInt: "4"
    },
    {
      id: 15,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      postem: "Chef de Services Production et Maintenance Applicatif",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      file: "3.pdf",
      agentimg: "oval1.png",
      nomInt: "4"
    },
    {
      id: 16,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      postem: "Chef de Services Production et Maintenance Applicatif",
      matricule: "060210",
      statut: false,
      file: "5.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
      nomInt: "4"
    },
    {
      id: 17,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      postem: "Chef de Services Production et Maintenance Applicatif",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      file: "2.pdf",
      agentimg: "oval1.png",
      nomInt: "4"
    },
    {
      id: 18,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      postem: "Chef de Services Production et Maintenance Applicatif",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      file: "5.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
      nomInt: "4"
    },
    {
      id: 19,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      statut: false,
      file: "1.pdf",
      agentimg: "oval1.png",
      pathfile: "../assets/doc/1.pdf",
      postem: "Chef de Services Production et Maintenance Applicatif",
      nomInt: "5"
    },
    {
      id: 20,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "Mon Jan 01 2021 00:00:00 GMT+0000 (Greenwich Mean Time)",
      dateFin: "Mon Dec 31 2022 00:00:00 GMT+0000 (Greenwich Mean Time)",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      theme: "Fin de Contrat",
      libele: "Le contrat de Lamine MBODJI fini dans 10 jours.",
      heure: "15h25",
      site: "www.2t-s.com",
      adagen: "Sacré Cœur 3 Pyrotechnie, Immeuble USAID à coté de la Pharmacie Mame Oumy GUEYE",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      postem: "Chef de Services Production et Maintenance Applicatif",
      matricule: "060210",
      statut: false,
      nomInt: "4",
      file: "4.pdf",
      agentimg: "oval.png",
      pathfile: "../assets/doc/1.pdf",
    },
  ];

 /* public diagrammes = [
    {
      id: 1,
      mois: "Janvier",
      finis: 85,
      nouveaux: 105,
      total: 900
    },
    {
      id: 2,
      mois: "Fevrier",
      finis: 95,
      nouveaux: 105,
      total: 385
    },
    {
      id: 3,
      mois: "Mars",
      finis: 85,
      nouveaux: 125,
      total: 596
    },
    {
      id: 4,
      mois: "Avril",
      finis: 105,
      nouveaux: 155,
      total: 386
    },
    {
      id: 5,
      mois: "Mai",
      finis: 25,
      nouveaux: 250,
      total: 606
    },
    {
      id: 6,
      mois: "Juin",
      finis: 99,
      nouveaux: 139,
      total: 408
    },
    {
      id: 7,
      mois: "Juillet",
      finis: 65,
      nouveaux: 117,
      total: 789
    },
    {
      id: 8,
      mois: "Aout",
      finis: 76,
      nouveaux: 312,
      total: 659
    },
    {
      id: 9,
      mois: "Septembre",
      finis: 19,
      nouveaux: 308,
      total: 908
    },
    {
      id: 10,
      mois: "Octobre",
      finis: 58,
      nouveaux: 111,
      total: 608
    },
    {
      id: 11,
      mois: "Noovembre",
      finis: 157,
      nouveaux: 28,
      total: 894
    },
    {
      id: 12,
      mois: "Decembre",
      finis: 17,
      nouveaux: 286,
      total: 789
    },
  ]; */

  private messageSource = new BehaviorSubject('default message');
  currentMessage = this.messageSource.asObservable();
  constructor() { }

  changeMessage(message: string) {
    this.messageSource.next(message)
  }

  public getData() {
    return this.data;
  }
  /*
  public getDiagramme() {
    return this.diagrammes;
  }  */

  
}
