import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  public data = [
    {
      id: 1,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 2,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 3,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 4,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 5,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 6,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 7,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 8,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 9,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 10,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "inter.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 11,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 12,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 13,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 14,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 15,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 16,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 17,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 18,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "4"
    },
    {
      id: 19,
      prenom: "Amadou Dieye",
      nom: "LEYE",
      poste: "Développeur Web",
      dateDebut: "25/12/2020",
      dateFin: "25/12/2022",
      tmp: "tmp_0254",
      agence: "Set Interim",
      dateNais: "10/12/1992",
      lieuNais: "Mbour",
      genre: "masculin",
      cni: "1 619 1992 2154",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "5"
    },
    {
      id: 20,
      prenom: "Aliou",
      nom: "DIOP",
      poste: "Développeur mobile",
      dateDebut: "28/02/2021",
      dateFin: "24/08/2021",
      tmp: "tmp_0844",
      agence: "Interim plus",
      dateNais: "27/03/1997",
      lieuNais: "Pikine",
      genre: "masculin",
      cni: "1 359 1997 2554",
      categorie: "Cadre C1C",
      structure: "Sonatel SA",
      direction: "DST",
      pole: "DD",
      departement: "DASI",
      service: "PMA",
      manager: "Madiagne SYLLA",
      email: "amadou.dieye.leye@orange-sonatel.com",
      telephone: "+ 221 33 824 91 31",
      adresse: "mbour",
      photo: "manager.png",
      matricule: "060210",
      nomInt: "4"
    },
  ]
  constructor() { }

  public getEvents() {
    return this.data;
  }
}
